//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SduHealthier.Core {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SduHealthier.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoginUrl {
            get {
                return ResourceManager.GetString("LoginUrl", resourceCulture);
            }
        }
        
        internal static string ServiceUrl {
            get {
                return ResourceManager.GetString("ServiceUrl", resourceCulture);
            }
        }
        
        internal static string ServiceHomeUrl {
            get {
                return ResourceManager.GetString("ServiceHomeUrl", resourceCulture);
            }
        }
        
        internal static string ServeApplyUrlTemp {
            get {
                return ResourceManager.GetString("ServeApplyUrlTemp", resourceCulture);
            }
        }
        
        internal static string CheckServiceUrl {
            get {
                return ResourceManager.GetString("CheckServiceUrl", resourceCulture);
            }
        }
        
        internal static string ServeInfoUrl {
            get {
                return ResourceManager.GetString("ServeInfoUrl", resourceCulture);
            }
        }
        
        internal static string GetServeApplyUrl {
            get {
                return ResourceManager.GetString("GetServeApplyUrl", resourceCulture);
            }
        }
        
        internal static string GetContinueServiceUrl {
            get {
                return ResourceManager.GetString("GetContinueServiceUrl", resourceCulture);
            }
        }
        
        internal static string ServiceLogoutUrl {
            get {
                return ResourceManager.GetString("ServiceLogoutUrl", resourceCulture);
            }
        }
        
        internal static string CasLogoutUrl {
            get {
                return ResourceManager.GetString("CasLogoutUrl", resourceCulture);
            }
        }
        
        internal static string PortalLogoutUrl {
            get {
                return ResourceManager.GetString("PortalLogoutUrl", resourceCulture);
            }
        }
        
        internal static string ServeBaseUrl {
            get {
                return ResourceManager.GetString("ServeBaseUrl", resourceCulture);
            }
        }
        
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
    }
}
